version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: fastapi_service
    ports:
      - "8000:8000"
    volumes:
      - .:/app

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: streamlit_service
    ports:
      - "8501:8501"
    depends_on:
      - api
    volumes:
      - .:/app
    devices:
      - "/dev/video0:/dev/video0"  # Monter la caméra dans le conteneur
    privileged: true               # Donner des droits supplémentaires pour accéder aux périphériques